Vagrant.configure("2") do |config|
  # grab our box..
  config.vm.box = "kmfarley11/inspirado-x86"

  # config web server access to localhost:8931 (host) -> port 80 (guest), resolve port collisions
  #config.vm.network :forwarded_port, guest: 80, host: 8931, auto_correct: true

  # shared folder access
  #config.vm.synced_folder "./", "/var/www", create: true, group: "www-data", owner: "www-data"

  # config provider (change / enforce memory etc.)
  # see VBoxManage for more info
  config.vm.provider "virtualbox" do |v|
    v.name = "Inspirado BBBW x86"
    v.customize ["modifyvm", :id, "--memory", "512"]
  end

  # setup provisioning (special commands / packages etc)
  config.vm.provision "shell" do |s|
    s.path = "provision/setup.sh"
  end
end
